alias fzfcd="cd \"\$(find ~/Documents/ -type d | fzf)\""
alias cb="xclip -selection clipboard"
alias yt="ytfzf"
alias cdskey="cat ~/Documents/class/S25/CDS\ 101/keys/github_key.txt | cb"
alias nvimconfig="nvim ~/.config/nvim/init.lua"
alias lock="betterlockscreen -l"
alias cd="z"
